name: OpenBSD

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  testopenbsd:
    runs-on: macos-12
    name: CI OpenBSD
    steps:
      - uses: actions/checkout@v3
      - name: Build and test in OpenBSD
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: openbsd
          architecture: x86-64
          version: '7.2'
          shell: bash
          cpu_count: 3
          run: |
            sudo pkg_add ninja cmake
            pkg_info
            sysctl kern.version
            sysctl hw
            .github/s2n_bsd.sh
      - name: upload test results
        if: ${{ failure()  }}
        uses: actions/upload-artifact@master
        with:
          name: all_test_output
          path: |
            output
